export const events = [
  {
    id: "1",
    title: "Drake Concert",
    date: "2026-05-01",
    location: "NYC",
    price: 120,

    fees: {
      service: 10,
      tax: 5,
    },

    deals: [
      "10% student discount",
      "Buy 2 get 1 free",
    ],

    budget: [
      { type: "Standard", price: 80 },
      { type: "VIP", price: 200 },
    ],

    notify: true,
  },
{
  id: "2",
  title: "Shakira Live",
  date: "2026-06-10",
  location: "Miami",
  price: 150,
  fees: { service: 12, tax: 8 },
  deals: ["Free drink with ticket"],
  budget: [
    { type: "Standard", price: 150 },
    { type: "VIP", price: 250 },
  ],
  notify: true,
},
{
  id: "3",
  title: "Taylor Swift Tour",
  date: "2026-07-15",
  location: "Los Angeles",
  price: 300,
  fees: { service: 20, tax: 15 },
  deals: ["Early access tickets"],
  budget: [
    { type: "Standard", price: 300 },
    { type: "VIP", price: 500 },
  ],
  notify: true,
},
{
  id: "4",
  title: "Ca7riel & Paco Amoroso",
  date: "2026-08-05",
  location: "Buenos Aires",
  price: 90,
  fees: { service: 8, tax: 4 },
  deals: ["Group discount"],
  budget: [
    { type: "Standard", price: 90 },
    { type: "VIP", price: 140 },
  ],
  notify: false,
},
{
  id: "5",
  title: "Rosalia World Tour",
  date: "2026-09-12",
  location: "Barcelona",
  price: 180,
  fees: { service: 15, tax: 10 },
  deals: ["Merch bundle"],
  budget: [
    { type: "Standard", price: 180 },
    { type: "VIP", price: 300 },
  ],
  notify: true,
},
{
  id: "6",
  title: "Ralphie Choo Live",
  date: "2026-04-20",
  location: "Madrid",
  price: 70,
  fees: { service: 5, tax: 3 },
  deals: ["Student discount"],
  budget: [
    { type: "Standard", price: 70 },
    { type: "VIP", price: 110 },
  ],
  notify: false,
},
{
  id: "7",
  title: "Fred Again.. Concert",
  date: "2026-10-01",
  location: "London",
  price: 200,
  fees: { service: 18, tax: 12 },
  deals: ["VIP backstage pass"],
  budget: [
    { type: "Standard", price: 200 },
    { type: "VIP", price: 350 },
  ],
  notify: true,
},
{
  id: "8",
  title: "Bjork Experience",
  date: "2026-11-11",
  location: "Reykjavik",
  price: 220,
  fees: { service: 20, tax: 10 },
  deals: ["Exclusive visuals"],
  budget: [
    { type: "Standard", price: 220 },
    { type: "VIP", price: 400 },
  ],
  notify: true,
},
{
  id: "9",
  title: "Caramelos de Cianuro",
  date: "2026-06-22",
  location: "Caracas",
  price: 80,
  fees: { service: 6, tax: 4 },
  deals: ["Free merch"],
  budget: [
    { type: "Standard", price: 80 },
    { type: "VIP", price: 130 },
  ],
  notify: false,
},
{
  id: "10",
  title: "Rawayana Live",
  date: "2026-07-30",
  location: "Mexico City",
  price: 95,
  fees: { service: 7, tax: 5 },
  deals: ["Summer special"],
  budget: [
    { type: "Standard", price: 95 },
    { type: "VIP", price: 150 },
  ],
  notify: true,
},
{
  id: "11",
  title: "Lindsey Stirling Tour",
  date: "2026-12-05",
  location: "Chicago",
  price: 160,
  fees: { service: 12, tax: 9 },
  deals: ["Meet & greet"],
  budget: [
    { type: "Standard", price: 160 },
    { type: "VIP", price: 280 },
  ],
  notify: true,
}
];
